### ISSUE TITLE
Allow variable-cost cells in pathfinding

### ISSUE THREAD

**Issue by alexjurkiewicz** [ondras/rot.js#115]
I noticed that A* pathfinding implementation calls its passability callback to determine if the sourceX,sourceY cell is passable. In my game this is a problem, since monsters block movement and the monster I'm pathfinding for therefore blocks its own movement! I work around this by creating the callback dynamically, and ignoring the source monster:

(typescript)
```typescript
  /**
   * Build a function that checks if a point is passable, ignoring a given
   * entity. We need this so entities do not block themselves while pathfinding!
   * @param e Entity to ignore.
   */
  private passableCallbackFactory(e: Entity): (x: number, y: number) => boolean {
    return (x, y) => {
      if (!inRange(x, 0, this.MAX_X) || !inRange(y, 0, this.MAX_Y)) {
        return false;
      }
      const entities = entitiesAt(x, y);
      // Don't let entities block themselves
      if (entities === [e]) { return true; }
      // Otherwise, the tile is passable if there are no entities
      return entities.length === 0;
    };
```

Could the pathfinding algorithm be changed to assume the starting position is passable?

**Comment by ondras** [comment]
This is more tricky than it looks. Partly because I would like to maintain consistency between the `AStar` and `Dijkstra` pathfinders.

The Dijkstra algorithm works by computing distances from **every** source cell to a particular target. That is why the `[toX, toY]` coords are fixed by passing them to `ROT.Path.Dijkstra` constructor, while `[fromX, fromY]` can be modified by calling `.compute()` with different arguments.

This means that the actual underlying computation is totally unrelated to the starting position. The topology used (i.e. __what neighbors a particular cell has__) is expected to by consistent and immutable for every single `.compute()` call. But your request (a very reasonable one!) implies that you want different topologies for different `.compute()` calls.

I am really not sure how to implement the requested behavior, given the current state of the API/implementation of the `ROT.Path.Dijkstra` pathfinder. On the other hand, I see no problem with your approach to the issue -- that is why the `passableCallback` exists; to provide enough flexibility for all situations.

**Comment by alexjurkiewicz** [comment]
Fair enough! While we're on the subject I have another feature request
which I don't think I can implement myself: different cell traversal costs.
Maybe mud tiles cost 2x to move through, or similar. Would this be
possible?!

**Comment by ondras** [comment]
> I have another feature request which I don't think I can implement myself: different cell traversal costs. Maybe mud tiles cost 2x to move through, or similar. Would this be possible?!

Yes, and I think that we can even re-use the current API for that. The `passableCallback` can return a numeric value, representing a relative traversal cost. This behavior might be implemented for both `AStar` and `Dijkstra` pathfinders.

I am out of time to do this properly now, but feel free to open an Issue for this feature. Someone else might be interested in implementing it or I might find some time in the future.
