### ISSUE TITLE
Support for static maps?

### ISSUE THREAD

**Issue by TimTCrouch** [ondras/rot.js#173]
I have been looking into using rot.js for a roguelike-like project, but one that does not include randomly generated maps. Rather, I would like to create the maps by hand, save them into some kind of matrix format and then import them into a rot.js-powered game. Of course it would be trivial to simply loop through my static matrix and draw() my own map to the display. But I am also wanting to take advantage of other map-related functionality such as FOV. I have looked through the Map code but it seems like they all assume generation. Maybe I am moving in the wrong direction. 

Does rot.js support creating a map with static tiles? At first I thought the Map.create callback was the ticket, but it seems to just be a way to get the generated tiles back out of the procedural generation algorithm so you can record them for displaying and other logic. 

Thanks for any assistance!

**Comment by ondras** [comment]
Hi @TimTCrouch,

you are not forced to use generated maps in order to leverage other parts of rot.js, such as FOV or Pathfinding. You are completely free to use any data structure for your map; that is why you provide *callbacks* to FOV/pathfinding.

For instance: you can save your map data to a text file and read that back into a an array of strings (lines). Say you now have:

```js
var map = [
  "####",
  "#..#",
  "#..#",
  "####"
];
```

Next, we will create a callback used by the FOV algorithm to provide access into our data structure:

```js
function lightPasses(x, y) {
  return map[y].charAt(x) == ".";
}
```

Finally, we can create a FOV and output its data to a console:

```js
var fov = new ROT.FOV.PreciseShadowcasting(lightPasses);

fov.compute(1, 1, 10, function(x, y, r, visibility) {
  console.log(x, y, r, visibility);
});
```

**Comment by TimTCrouch** [comment]
Thank you for this! I guess I sort of misunderstood the case of the callbacks based on some code I had seen. I appreciate it!
