### ISSUE TITLE
please move prototype modifications to a utility class

### ISSUE THREAD

**Issue by seiyria** [ondras/rot.js#69]
This gets in the way of other libraries doing things and it causes unexpected results. For example, I'm trying to use [d20.js](https://github.com/michaelenger/d20.js/blob/master/d20.js) but any time I use their roll function, I get this:

```
41function () {
	if (!this.length) { return null; }
	return this[Math.floor(ROT.RNG.getUniform() * this.length)];
}function () {
	var result = [];
	while (this.length) {
		var index = this.indexOf(this.random());
		result.push(this.splice(index, 1)[0]);
	}
	return result;
}
```

**Comment by ondras** [comment]
Hi,

this is not really a bug in rot.js. Instead, this is an issue of the d20.js library and their incorrect iteration mechanisms.

You see, in JS, there are two syntactic approaches to iteration. The `for (p in o)` syntax which **enumerates** properties and the `for (i=0; i<...; i++)` that traverses numerically indexed values. It is a well-known fact [1] that JS array shall be iterated only using the latter syntax -- precisely because the key enumeration approach might accidentaly list additional array features, such as prototypal enhancements.

In this particular case, the offending code is https://github.com/michaelenger/d20.js/blob/master/d20.js#L26 -- an Array iterated via `for .. in`. I would recommend submitting an issue for their project instead. If you wish, I can help you with a pull request.

(Side, somewhat unrelated note: adding stuff to primordial object prototypes might pose problems due to naming collisions. There are, however, cases where it is absolutely necessary to augment `Array.prototype` and similar.)

[1] http://stackoverflow.com/questions/500504/why-is-using-for-in-with-array-iteration-such-a-bad-idea

**Comment by seiyria** [comment]
I totally get this, and I realize they're doing something they shouldn't. I also do not think you should be modifying prototypes on natives, either, though, which is why I bring it up. 

In most of the cases, the prototype modifications you provide could be obtained easily from a third party like Lodash (`_.capitalize`, `_.shuffle`, `_.extend`, etc), and I think it's best to encourage using those libraries instead (they provide way more functionality too). The only thing that really isn't available is your `mod` function, but that's [pretty easy to set up if necessary](https://github.com/ondras/rot.js/blob/4834a8667db67d9d00ca206d91b65b74c892bb7a/src/js/number.js#L6-L8). 

Perhaps even just moving them to an optional `rot-util` package and preserving existing behavior would be fine, even, so long as it was optional.

**Comment by ondras** [comment]
Well, my opinion about native prototypes is obvious, so I am not going to change this without having a serious motivation to do so.

The issue with d20.js is not a reson for me, becuase this is clearly **their** faul (their crappy iteration would break elsewhere sooner or later -- think `Array.prototype.indexOf` polyfill for IE8-). So unless you point me to a well-defined naming collision, I think the prototypal enhancements are going to stay.

Generally speaking, I do not recommend any other 3rd party libraries. I have a strongly negative opinion about jQuery, underscore, lodash and others; for beginners, I recommend using just rot.js + vanilla JS.

Also please keep in mind that rot.js ships with its own RNG (both better and feature-richer than `Math.random`). You will not be able to leverage this when using d20.js or `_.shuffle`.

Note: while I have no problem with **careful** augmentation of primordial prototypes, I am **against** modifications of `Object.prototype`. This is not very relevant, I am mentioning it just for completeness.

**Comment by seiyria** [comment]
Sure, that's fine. I wanted to have this discussion just to see where you were on the spectrum. To be clear, I'm no longer using d20.js, it's just an issue that came up whilst assessing it. I landed on [this dice roller](https://github.com/lordnull/dice.js) and I think the features are far better.

All this said, I should be clear as well: I don't mind polyfills for behavior that I would expect to exist (ie, default browser functions), but when it's more for utility functions, I think they should be in their own namespace so they don't accidentally collide with someone elses library and so the prototypes act more predictably.

You're right, it is definitely their fault. I'm not defending them, but it is an honest mistake and it could definitely trip someone up if they didn't totally understand how JS works, or if they wanted to use a great library that has a similar fault, but don't want to fork/PR it (or worse, if that library is depending on that behavior, _shudder_).

It's fine that you don't recommend those libraries, especially for beginners -- it might be confusing to them. That said, not everyone who uses your library is or will be a beginner. I think it's good to consider all of your audiences when making something as useful and general-purpose as this. 

While having a better RNG is definitely a good thing, I definitely do not always need one. If I'm shuffling an array for whatever reason, it's possible I don't really need it to be super random. That said, what I've used your RNG for so far is number generation (since all roguelikes should have a "fair" RNG). I've just sent @jdalton a tweet just to see whether or not lodash can be given a new RNG globally, if so, I think that might help out a little bit here.

**Comment by ondras** [comment]
The main strength of rot.js's `RNG` is **seedability**, which allows **reproducibility**. This is a very strong feature (particulatly in procedurally generated games), but to fully use it, you have to call `ROT.RNG.*` instead of `Math.random()` every single time you do random stuff, including array shuffling.

Also, for fun, I just implemented a simple dice roller in 120 bytes of JS: https://gist.github.com/ondras/42966b6be042ca83b21b#file-annotated-js :-)
