### ISSUE TITLE
A* Performance

### ISSUE THREAD

**Issue by seiyria** [ondras/rot.js#70]
I've been working on an "automated" roguelike (see [here](http://plnkr.co/edit/miYo20GPQ0cxe5rlK7wk)). Currently, the game goes pretty fast - the player takes a turn every 50ms. Every 100 turns 1-3 enemies spawn, and when they do, there's a noticeable performance drop. Currently, all of the enemies are using A* to find their way to the player, but I'm wondering if that's a wise idea.

What sorts of options do I have here? Should I compute a weighted grid and use that (plus something like easystar) instead of using the callback-based ROT.AStar? Or am I just doing it wrong?

**Comment by seiyria** [comment]
Additionally, I think part of my problem is that somehow references to the AStar path are being held. Periodically, my game will just freeze and after doing a snapshot via code, the allocation timeline looks like this:

![](http://i.imgur.com/hRTABaE.png)

But if I just don't do any pathfinding, it looks a bit more normal, like this: 

![](http://i.imgur.com/Ig133dW.png)

My code looks like this:
```js
  stepTowards(target) {
    let path = [];
    let canPass = (x, y) => {
      let isMe = this.x === x && this.y === y;
      let isTarget = target.x === x && this.y === target.y;
      return GameState.world.isTilePassable(x, y, this.z) || isMe || isTarget;
    };
    let astar = new ROT.Path.AStar(target.x, target.y, canPass, {topology: 8});
    let addPath = (x, y) => path.push({x, y});
    astar.compute(this.x, this.y, addPath);
    
    path.shift();
    let step = path.shift();
    if(!step) return false;
    
    this.moveTo(step.x, step.y);
    return true;
  }
```

It doesn't seem to be holding any references, so I'm not sure what the performance hit is for, really.

**Comment by ondras** [comment]
First of all, kudos for using a full-scale ES6, including the System API! I am very happy to see ES6 used in the wild.

This issue might be a pretty tough nut to crack. First of all, do you observe similar behavior also in Firefox (I assume your screenshots are from Chrome, right?) ? I tried your code in my Firefox and I did not notice any suttering on monster spawn.

Generally speaking, I would say that the described/measured behavior is caused by GC pauses. There is very little in the JS world to do in order to make GC behave; in most cases, the GC is much smarter than the JS developer.

(The actual CPU performance of the A* algo does not seem the be a problem, right? The (de)allocation is, instead...)

Every `ROT.Path.AStar` invocation comes with a reasonably heavy memory allocation cost, as all the traversed graph data needs to be stored during the computation. I am no A* guru so I am not able to tell if this memory requirement can be relaxed somehow. You can, if you wish, explicitely empty the `this._todo` and `this._done` fields once the `compute()` is finished (see https://github.com/ondras/rot.js/blob/master/src/path/astar.js). This **might** give the GC some earlier hint, but I really have no idea.

You can also double-check the transpiled code to see if the `let astar` definition does not accidentally end up being some memory leak or something.

As far as your game logic goes, you might try computing a **Dijkstra** path on every **player** move. This precomputed Dijkstra map can be re-used by all enemies, as they share a common goal (reaching the player). Again, I have no idea if this can improve your situation.

You can also limit the pathfinding algo to some radius (forbid paths that are longer than R distance from the player). This is more realistic and reduces the amount of memory allocated for pathfinding.

**Comment by seiyria** [comment]
Thanks. I really am liking ES6 and being able to use it with plunker is a dream come true. It's also fun, because I've not seen many projects use full ES6, so I think I can share what I learned afterwards! From top to bottom...

* Yes, this is chrome. It seems you're right; it's not happening at all in firefox. I may have to find someone to escalate that to. It definitely does not seem to be the performance of A*, but rather deallocation like you said - I think the algorithm is implemented fine and for my purposes it's correct.

* I'll try explicitly setting `todo` and `done` if your other suggestions don't work, but this seems like it might help as well. I don't know as much about the GC as I probably should, I'll admit.

* The transpiled code is as below. It just turns it into `var`:

```js
          key: "stepTowards",
          value: function stepTowards(target) {
            var _this2 = this;

            var path = [];
            var canPass = function canPass(x, y) {
              var isMe = _this2.x === x && _this2.y === y;
              var isTarget = target.x === x && _this2.y === target.y;
              return GameState.world.isTilePassable(x, y, _this2.z) || isMe || isTarget;
            };
            var astar = new ROT.Path.AStar(target.x, target.y, canPass, { topology: 8 });
            var addPath = function addPath(x, y) {
              return path.push({ x: x, y: y });
            };
            astar.compute(this.x, this.y, addPath);

            path.shift();
            var step = path.shift();
            if (!step) return false;

            this.moveTo(step.x, step.y);
            return true;
          }
```
... so I think this is fine.

* I think sharing a map is a wise choice actually, and it's not one I'd given thought to. This seems like a pretty obvious optimization and I'll probably try this first.

* Is the radius limiter built into `ROT` or is that something I do myself? I ask because I'm not seeing it in the docs, so, I imagine that in the callbacks, I just check the distances between the position and the player and ignore if it's too far?

I'll give this a try tomorrow and let you know what I come up with.

**Comment by seiyria** [comment]
Gotta say, that Dijkstra suggestion did it for me. I'm not noticing immediate hiccups upon monster spawning now, so I think I'll stick with this for a while. Thanks for the help!

FYI: I tried setting `todo` and `done` to undefined (and deleting them) but that didn't really do much.

**Comment by ondras** [comment]
Cool, good to know. I am pretty certain I saw some (unrelated to rot.js) GC reports in Chrome, especially when compared to Firefox before.

The range limiting would be done exactly as you described, as part of the user callback function.
