### ISSUE TITLE
Insert X turns into the scheduler

### ISSUE THREAD

**Issue by seiyria** [ondras/rot.js#71]
I'm using the speed scheduler, and I'm just now adding projectiles to my project. I figure the least hacky way to implement projectiles is to add them to the scheduler and give them turns, but I'm not sure how to add them and make sure the next X turns are theirs (where X is the number of steps between the caster and the target). Is this currently possible, or is there a better way? I've read a bit about the action scheduler, but I'm not sure it fits my use-case entirely.

**Comment by ondras** [comment]
Kyle, unless you want your projectile to be intercepted in mid-flight (i.e. something happens during the flight), I would suggest evading the scheduler completely. Once the projectile is launched, pause the game (`ROT.Engine` if you use this) and use the `requestAnimationFrame` technique to perform the flight. Once it hits something, un-pause the game loop. I see no advantage of scheduling individual flight elements as regular actions.

**Comment by seiyria** [comment]
That's what my current implementation was going to do (ie, stop and re-start after) but I wasn't sure how to make the game pause, then re-draw every step (which would probably be 100ms/step) without using setTimeout. I wanted to avoid doing any timeouts or intervals since that seems like a bad choice here.

Do you mean the browsers requestAnimationFrame or something internal to ROT?

**Comment by ondras** [comment]
I mean the native `requestAnimationFrame`. Can you elaborate on why setTimeout/setInterval would be a bad choice?

Also, do you have any strong opinion regarding **what** is allowed to happen during the projectile's flight?

**Comment by seiyria** [comment]
It's not that it'd be a bad choice, I just think it's weird to do this:

```js
path = [] //this path is from the caster to the target
game.engine.stop();
let interval = setInterval( () => {
  let step = path.shift();
  // move projectile
  // call an external update function (can't redraw the ROT.Display since the engine is locked, or can I?)
  // if we have no more steps, cancel the interval
}, 100)
```

It seems like a case the engine should be able to handle (although if it shouldn't be, I'm definitely curious why - I'm pretty new to roguelike development here).

As for what can happen during the projectiles flight.. right now I'm operating under the assumption that the only people acting on it would be the caster and the target, where the caster could fumble (and it would not reach the target), the caster could hit (normal outcome), or the caster could overshoot and possibly hit something else, or a wall. All of these can be handled in the path computation and wouldn't need any special consideration outside of that. What sort of things were you thinking?

**Comment by ondras** [comment]
The `ROT.Engine` and `ROT.Display` are not connected in any way, their instance have no reference to each other. Your display will normally redraw, independently on the engine's state.

The `ROT.Engine` is meant as a simple wrapper atop those various scheduling algos. You are by no means required to use it; its main strength is the counting lock for cases where multiple sources (animations, for example!) need to pause and unpause the game flow. In these days, Promises come to mind as a way to handle this. `ROT.Engine` is much older than (ES6) Promises.

Generally, I would use a Scheduler (and therefore an Engine as well) for things that need to be planned/scheduled in order to maintain some order (pun intended :smile: ). If the animation interrupts the game flow, stopping all actions during the flight, there is no real use in treating it like a repeating actor.

For me, it makes sense to treat the flight animation precisely as you described: it launches as a result of an entity's turn; its outcome is pre-computed and the turn engine is paused during the flight. Once the projectile resolves, the engine continues scheduling actors.

**Comment by ondras** [comment]
It should be noted that recent rot.js builds come with a Promise-aware `ROT.Engine`. If the `act` method returns a Promise instance, the engine will pause itself and unpause when the promise resolves.

**Comment by seiyria** [comment]
This makes sense. I'll make it work that way then. Thanks for your feedback!
